version: "3.8"

services:
  webserver:
    restart: unless-stopped
    container_name: webserver
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: ghettohustlers256@gmail.com
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt

  node:
    build:
      context: ./app
    container_name: node
    user: node
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

volumes:
  letsencrypt:
