version: "3.7"

services:
  app:
    build:
      context: ./app
    container_name: app
    # ports:
    #   - "80:3000"
    #   - "443:443"
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/letsencrypt/www:/tmp/letsencrypt/www
