version: "3.7"

services:
  webserver:
    container_name: webserver
    image: nginx:1.21.0-alpine
    restart: unless-stopped
    volumes:
      - /docker/nginx/conf:/etc/nginx:ro
      - /docker/nginx/www/:/var/www:ro
      - /certs/letsencrypt:/etc/letsencrypt:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/log:/var/log
    ports:
      - 80:80
      - 443:443
    depends_on:
      - node-server

  # Run the node application
  node-server:
    container_name: node-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./app
